import json
import logging
import os
from typing import List, Dict, TypedDict

from dotenv import load_dotenv
from pydantic import BaseModel, Field, ValidationError
from langgraph.graph import StateGraph, END
from huggingface_hub import InferenceClient

# Configure logging for the console
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

# Load environment variables from .env
load_dotenv()

# Get Hugging Face token
hf_token = os.getenv("HUGGINGFACEHUB_API_TOKEN")

if not hf_token:
    raise ValueError(
        "HUGGINGFACEHUB_API_TOKEN not found. Create a .env file and add your token."
    )

# ==========================================
# 1. PYDANTIC SCHEMAS (Structured Output)
# ==========================================

class DeepInsight(BaseModel):
    category: str = Field(
        ..., 
        description="Must be one of: 'Behavioral Pattern', 'Cognitive Load', 'Physiological Risk', or 'Protective Factor'."
    )
    observation: str = Field(
        ..., 
        description="What the data reveals based on the mathematical drivers."
    )
    clinical_rationale: str = Field(
        ..., 
        description="The psychological or physiological reason why this matters to the user's stress."
    )
    action_step: str = Field(
        ..., 
        description="One highly specific, achievable micro-action the user can take today."
    )

class AdvancedDashboardInsights(BaseModel):
    daily_summary: str = Field(
        ..., 
        description="A warm, compassionate 2-sentence summary of the user's day based on the data."
    )
    core_bottleneck: str = Field(
        ..., 
        description="The primary driver of stress today."
    )
    deep_analysis: List[DeepInsight] = Field(
        ..., 
        description="Exactly 4 distinct, deep insights analyzing the intersection of their habits and stressors.",
        min_length=4,
        max_length=5
    )

# ==========================================
# 2. LANGGRAPH STATE DEFINITION
# ==========================================

class PipelineState(TypedDict):
    """The data structure that flows through our pipeline."""
    raw_metrics: dict              # Input from Component 1
    rlhf_rules: dict               # Input from Component 4
    analysis_plan: str             # Generated by Planner Node
    safety_trigger: bool           # Generated by Planner Node
    final_insights_json: dict      # Generated by Analyzer Node

# ==========================================
# 4. GRAPH NODES
# ==========================================

def planner_node(state: PipelineState) -> Dict:
    """Evaluates raw metrics to determine the analytical strategy."""
    logging.info("Executing Planner Node...")
    metrics = state.get("raw_metrics", {})
    score = metrics.get("predicted_stress_score", 0.0)
    
    if score > 0.75:
        plan = (
            "CRITICAL: High stress detected. Focus analysis on immediate risk mitigation."
        )
        safety = True
    else:
        plan = (
            "STANDARD: Normal stress variance. Focus on baseline habit tracking."
        )
        safety = False
        
    return {"analysis_plan": plan, "safety_trigger": safety}

def analyzer_node(state: PipelineState) -> Dict:
    """Uses Hugging Face API to translate metrics into JSON insights."""
    logging.info("Executing Analyzer Node...")
    metrics = state["raw_metrics"]
    plan = state["analysis_plan"]
    rlhf_rules = state.get("rlhf_rules", {})
    
    # Format the rules for the prompt
    avoid_list = ", ".join(rlhf_rules.get("avoid_interventions", ["none"]))
    prefer_list = ", ".join(rlhf_rules.get("preferred_interventions", ["general_mindfulness"]))
    
    # We pass the schema explicitly to the model to guide its formatting
    schema_definition = AdvancedDashboardInsights.model_json_schema()
    
    prompt = f"""
    You are the clinical statistics engine of Serene.
    
    Execution Strategy: {plan}
    
    User Metrics & Mathematical Drivers:
    {json.dumps(metrics, indent=2)}
    
    [USER BOUNDARIES]
    When generating the 'action_step' for each insight:
    - Strongly favor actions related to: {prefer_list}
    - CRITICAL: Do NOT suggest actions related to: {avoid_list}
    
    Rules for Analysis:
    1. Generate exactly 4 deep insights synthesizing these numbers.
    2. Respond with ONLY valid JSON matching this schema:
    {json.dumps(schema_definition, indent=2)}
    """
    
    logging.info("Waiting for Hugging Face Serverless API... (This may take 30s if cold)")
    
    try:
        response = client.chat_completion(
            messages=[
                {"role": "system", "content": "You are a precise, clinical JSON generator. Output only valid JSON."},
                {"role": "user", "content": prompt}
            ],
            response_format={"type": "json_object"}, # Force JSON mode natively
            max_tokens=1000,
            temperature=0.2
        )
        
        # Extract the string response and parse it
        raw_json_str = response.choices[0].message.content
        parsed_dict = json.loads(raw_json_str)
        
        # Validate against our Pydantic schema to ensure it's structurally sound
        validated_data = AdvancedDashboardInsights(**parsed_dict)
        return {"final_insights_json": validated_data.model_dump()}
        
    except ValidationError as e:
        logging.error(f"Pydantic Validation Error: The model output malformed JSON. {e}")
        return {"final_insights_json": {"error": "Malformed JSON from LLM"}}
    except Exception as e:
        logging.error(f"Hugging Face Connection Error: {e}")
        return {"final_insights_json": {"error": str(e)}}

# ==========================================
# 5. BUILD AND COMPILE THE PIPELINE
# ==========================================

def build_insights_pipeline():
    workflow = StateGraph(PipelineState)
    workflow.add_node("planner", planner_node)
    workflow.add_node("analyzer", analyzer_node)
    workflow.set_entry_point("planner")
    workflow.add_edge("planner", "analyzer")
    workflow.add_edge("analyzer", END)
    return workflow.compile()

def generate_insights(ml_payload: dict, rlhf_rules: dict = None) -> dict:
    """Wrapper function to execute the pipeline."""
    pipeline = build_insights_pipeline()
    final_state = pipeline.invoke({
        "raw_metrics": ml_payload["raw_metrics"],
        "rlhf_rules": rlhf_rules or {}
    })
    return final_state.get("final_insights_json", {})

# ==========================================
# 6. EXECUTION 
# ==========================================

if __name__ == "__main__":
    print("\n--- Serene Component 2: Insights Pipeline Initialization ---")
    
    mock_ml_payload = {
        "raw_metrics": {
            "predicted_stress_score": 0.82,
            "top_mathematical_drivers": {
                "work_study_hours": 0.18,      
                "sleep_avg_hours": 0.14,       
                "Exam Anxiety": 0.08,          
                "wellness_points": -0.05       
            }
        }
    }
    
    mock_rlhf_rules = {
        "preferred_interventions": ["cognitive_reframing", "digital_detox"],
        "avoid_interventions": ["physical_movement"]
    }

    returned_insights = generate_insights(mock_ml_payload, mock_rlhf_rules)
    
    print("\n--- Final Validated Output for Serene Dashboard ---")
    print(json.dumps(returned_insights, indent=2))