import json
import logging
import os
from typing import List, Dict, TypedDict

from dotenv import load_dotenv
from pydantic import BaseModel, Field, ValidationError
from langgraph.graph import StateGraph, END
from huggingface_hub import InferenceClient

# Configure logging for the console
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

# Load environment variables from .env
load_dotenv()

# Get Hugging Face token
hf_token = os.getenv("HUGGINGFACEHUB_API_TOKEN")

if not hf_token:
    raise ValueError(
        "HUGGINGFACEHUB_API_TOKEN not found. Create a .env file and add your token."
    )

# ==========================================
# 1. PYDANTIC SCHEMAS (Structured Output)
# ==========================================

class DeepInsight(BaseModel):
    category: str = Field(
        ..., 
        description="Must be one of: 'Behavioral Pattern', 'Cognitive Load', 'Physiological Risk', or 'Protective Factor'."
    )
    observation: str = Field(
        ..., 
        description="A warm, relatable everyday observation about their habits, mood, or environment."
    )
    clinical_rationale: str = Field(
        ..., 
        description="A gentle, empathetic explanation of why this matters for their emotional and physical well-being."
    )
    action_step: str = Field(
        ..., 
        description="One simple, comforting, and easily achievable micro-action they can take today."
    )

class AdvancedDashboardInsights(BaseModel):
    daily_summary: str = Field(
        ..., 
        description="A warm, compassionate, and deeply human 2-sentence reflection on the user's day."
    )
    core_bottleneck: str = Field(
        ..., 
        description="The primary stress theme today, framed in a gentle and supportive way."
    )
    deep_analysis: List[DeepInsight] = Field(
        ..., 
        description="Exactly 4 distinct, supportive insights analyzing the intersection of their habits and stressors.",
        min_length=4,
        max_length=5
    )

# ==========================================
# 2. LANGGRAPH STATE DEFINITION
# ==========================================

class PipelineState(TypedDict):
    """The data structure that flows through our pipeline."""
    raw_metrics: dict              # Input from Component 1
    rlhf_rules: dict               # Input from Component 4 (RLHF)
    analysis_plan: str             # Generated by Planner Node
    safety_trigger: bool           # Generated by Planner Node
    final_insights_json: dict      # Generated by Analyzer Node

# ==========================================
# 3. HUGGING FACE NATIVE CLIENT
# ==========================================
# Using the official Hugging Face client instead of OpenAI/Instructor 
# to bypass connection routing errors on the Serverless API.
client = InferenceClient(
    model="microsoft/phi-4",
    token=hf_token,
    timeout=120.0 # 2 minute timeout for cold starts
)

# ==========================================
# 4. GRAPH NODES
# ==========================================

def planner_node(state: PipelineState) -> Dict:
    """Evaluates raw metrics to determine the analytical strategy."""
    logging.info("Executing Planner Node...")
    metrics = state.get("raw_metrics", {})
    score = metrics.get("predicted_stress_score", 0.0)
    
    if score > 0.75:
        plan = (
            "CRITICAL: High stress detected. Focus analysis on immediate risk mitigation."
        )
        safety = True
    else:
        plan = (
            "STANDARD: Normal stress variance. Focus on baseline habit tracking."
        )
        safety = False
        
    return {"analysis_plan": plan, "safety_trigger": safety}

def analyzer_node(state: PipelineState) -> Dict:
    """Uses Hugging Face API to translate metrics into JSON insights."""
    logging.info("Executing Analyzer Node...")
    metrics = state["raw_metrics"]
    plan = state["analysis_plan"]
    rlhf_rules = state.get("rlhf_rules", {})
    
    # Format the rules for the prompt
    avoid_list = ", ".join(rlhf_rules.get("avoid_interventions", ["none"]))
    prefer_list = ", ".join(rlhf_rules.get("preferred_interventions", ["general_mindfulness"]))
    
    prompt = f"""
    You are an empathetic, warm, and highly conversational wellness guide for Serene (NOT a clinical statistics engine). 
    Your goal is to translate the user's daily check-in metrics and stress factors into gentle, human, and easily understandable insights.
    
    Execution Strategy: {plan}
    
    User Metrics & Stress Factors:
    {json.dumps(metrics, indent=2)}
    
    [USER BOUNDARIES]
    When generating the 'action_step' for each insight:
    - Strongly favor actions related to: {prefer_list}
    - CRITICAL: Do NOT suggest actions related to: {avoid_list}
    
    Rules for Analysis:
    1. Generate exactly 4 distinct deep insights analyzing the intersection of habits and stressors.
    2. Categories must be one of: 'Behavioral Pattern', 'Cognitive Load', 'Physiological Risk', or 'Protective Factor'.
    3. Keep all responses warm, compassionate, conversational, and free of dry mathematical phrasing or statistics (do NOT mention specific coefficients like '0.18' or machine learning terminology).
    4. Respond with ONLY valid JSON matching this exact structure (do not echo this template, fill it in with actual data):
    {{
      "daily_summary": "A warm, comforting 2-sentence reflection on the user's day, acknowledging their feelings and activities without sounding like a data report.",
      "core_bottleneck": "The main theme or stress source of today, framed gently in a supportive way (e.g., 'Feeling a bit stretched thin between classes and work').",
      "deep_analysis": [
        {{
          "category": "Behavioral Pattern",
          "observation": "A warm and relatable observation about their habits or day (e.g., 'Your screen time was slightly higher today, which is totally understandable when studying hard').",
          "clinical_rationale": "A gentle, human explanation of why this matters for their well-being, translated from clinical concepts into friendly advice.",
          "action_step": "One small, comforting, and achievable step they can do today."
        }},
        {{
          "category": "Cognitive Load",
          "observation": "A relatable observation about their mental strain or stressors.",
          "clinical_rationale": "A compassionate explanation of how this affects their stress.",
          "action_step": "A comforting micro-step to ease the load."
        }},
        {{
          "category": "Physiological Risk",
          "observation": "A gentle observation about their body, sleep, or physical wellness.",
          "clinical_rationale": "A simple explanation of the connection between rest and stress.",
          "action_step": "An easy action step to promote physical rest."
        }},
        {{
          "category": "Protective Factor",
          "observation": "A warm celebration of something positive they did today.",
          "clinical_rationale": "An encouraging note on why this matters.",
          "action_step": "An encouraging micro-action to build on this."
        }}
      ]
    }}
    """
    
    logging.info("Waiting for Hugging Face Serverless API... (This may take 30s if cold)")
    
    try:
        response = client.chat_completion(
            messages=[
                {"role": "system", "content": "You are a warm, compassionate wellness guide. Output only valid JSON containing empathetic insights and gentle wellness reflections based on the user's stress metrics."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=1200,
            temperature=0.2
        )
        
        # Extract the string response and parse it
        raw_json_str = response.choices[0].message.content
        logging.info(f"DEBUG RAW RESPONSE: {repr(raw_json_str)}")
        
        # Clean markdown if present
        cleaned_str = raw_json_str.strip()
        if cleaned_str.startswith("```"):
            lines = cleaned_str.split("\n")
            if lines[0].startswith("```"): lines = lines[1:]
            if lines[-1].startswith("```"): lines = lines[:-1]
            cleaned_str = "\n".join(lines).strip()
            
        parsed_dict = json.loads(cleaned_str)
        
        # Validate against our Pydantic schema to ensure it's structurally sound
        validated_data = AdvancedDashboardInsights(**parsed_dict)
        return {"final_insights_json": validated_data.model_dump()}
        
    except ValidationError as e:
        logging.error(f"Pydantic Validation Error: The model output malformed JSON. {e}")
        return {"final_insights_json": {"error": "Malformed JSON from LLM"}}
    except Exception as e:
        logging.error(f"Hugging Face Connection Error: {e}")
        return {"final_insights_json": {"error": str(e)}}

# ==========================================
# 5. BUILD AND COMPILE THE PIPELINE
# ==========================================

def build_insights_pipeline():
    workflow = StateGraph(PipelineState)
    workflow.add_node("planner", planner_node)
    workflow.add_node("analyzer", analyzer_node)
    workflow.set_entry_point("planner")
    workflow.add_edge("planner", "analyzer")
    workflow.add_edge("analyzer", END)
    return workflow.compile()

def generate_insights(ml_payload: dict, rlhf_rules: dict = None) -> dict:
    """Wrapper function to execute the pipeline."""
    pipeline = build_insights_pipeline()
    final_state = pipeline.invoke({
        "raw_metrics": ml_payload["raw_metrics"],
        "rlhf_rules": rlhf_rules or {}
    })
    return final_state.get("final_insights_json", {})

# ==========================================
# 6. EXECUTION 
# ==========================================

if __name__ == "__main__":
    print("\n--- Serene Component 2: Insights Pipeline Initialization ---")
    
    mock_ml_payload = {
        "raw_metrics": {
            "predicted_stress_score": 0.82,
            "top_mathematical_drivers": {
                "work_study_hours": 0.18,      
                "sleep_avg_hours": 0.14,       
                "Exam Anxiety": 0.08,          
                "wellness_points": -0.05       
            }
        }
    }

    returned_insights = generate_insights(mock_ml_payload)
    
    print("\n--- Final Validated Output for Serene Dashboard ---")
    print(json.dumps(returned_insights, indent=2))